Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false