version: 2.1

executors:
  test_executor:
    working_directory: ~/sitemaps

    docker:
      - image: cimg/ruby:${RUBY_VERSION}

jobs:
  build:
    environment:
      RUBY_VERSION: << parameters.ruby_version >>
      ACTIVESUPPORT_VERSION: << parameters.activesupport_version >>
    executor: test_executor
    parameters:
      ruby_version:
        type: string
      activesupport_version:
        type: string
    steps:
      - checkout

      - restore_cache:
          keys:
            - sitemaps-cache-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
            - sitemaps-cache-v1-{{ arch }}-{{ .Branch }}
            - sitemaps-cache-v1

      - run:
          name: Bundle Install
          command: |
            bundle check --path=vendor/bundle || bundle install --clean --path vendor/bundle

      - save_cache:
          key: sitemaps-cache-v1-{{ arch }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - vendor/bundle

      - run:
          name: RSpec
          command: bundle exec rspec spec

      # Once lower-level offenses are resolved, the fail-level flags should be removed
      # so that any offense will cause the build to fail.
      - run:
          name: Rubocop
          command: bundle exec rubocop --fail-level warning --display-only-fail-level-offenses

workflows:
  build_and_test:
    jobs:
      - build:
          name: "Ruby << matrix.ruby_version >>, Active Support << matrix.activesupport_version >>"
          matrix:
            parameters:
              ruby_version:
                - 2.3.8
                - 2.4.10
                - 2.5.8
                - 2.6.7
                - 2.7.1
              activesupport_version:
                - 4.2.11.3
                - 5.1.7
                - 5.2.6
                - 6.0.3.7
                - 6.1.3.2
